#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cat <<EOF >>~/.env
# NKP
export NKP_VERSION=$(nkp version -o=json |jq -r '.nkp.gitVersion')
export CLUSTER_NAME="@@{CLUSTER_NAME}@@"
export NUTANIX_USER="@@{CRED_PC.username}@@"
export NUTANIX_PASSWORD="@@{CRED_PC.secret}@@"
export NUTANIX_ENDPOINT="@@{PC_ADDRESS}@@"
export NUTANIX_PORT="@@{PC_PORT}@@"
export MGMT_LB_IP_RANGE_STARTS="@@{MGMT_LB_IP_RANGE_STARTS}@@"
export MGMT_LB_IP_RANGE_ENDS="@@{MGMT_LB_IP_RANGE_ENDS}@@"
export CONTROL_PLANE_VIP_ADDRESS="@@{CONTROL_PLANE_VIP_ADDRESS}@@"
export NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME="@@{MACHINE_TEMPLATE_IMAGE_NAME}@@"
export NUTANIX_PRISM_ELEMENT_CLUSTER_NAME="@@{PRISM_ELEMENT_CLUSTER_NAME}@@"
export NUTANIX_SUBNET_NAME="@@{SUBNET_NAME}@@"
export NUTANIX_STORAGE_CONTAINER_NAME="@@{STORAGE_CONTAINER_NAME}@@"
export REGISTRY_MIRROR_URL="@@{CONTAINER_REGISTRY_MIRROR}@@"
export NO_COLOR=1
export MGMT_LB_IP_RANGE_USERS_STARTS="@@{MGMT_LB_IP_RANGE_USERS_STARTS}@@"
export MGMT_LB_IP_RANGE_USERS_ENDS="@@{MGMT_LB_IP_RANGE_USERS_ENDS}@@"
# LDAP
export DOMAIN=@@{DOMAIN}@@
export BINDDN='@@{BINDDN}@@'
export BINDPW='@@{BINDPW}@@'
export LDAP_HOST=@@{LDAP_HOST}@@
export LDAP_PORT='@@{LDAP_PORT}@@'
export NO_SSL='@@{NO_SSL}@@'
export SKIP_SSL_VERIFICATION='@@{SKIP_SSL_VERIFICATION}@@'
export START_TLS='@@{START_TLS}@@'
export LDAP_SEARCH_USERS='@@{LDAP_SEARCH_USERS}@@'
export LDAP_SEARCH_GROUPS='@@{LDAP_SEARCH_GROUPS}@@'
# Management Workspace
export MANAGEMENT_WORKSPACE_APPS='@@{MANAGEMENT_WORKSPACE_APPS}@@'
# Default Workspace
export INFRA_PROVIDER_NAME=pc
export DEFAULT_WORKSPACE_APPS='@@{DEFAULT_WORKSPACE_APPS}@@'
# CSI Files
export PE_VIP_ADDRESS=@@{PE_VIP_ADDRESS}@@
export NUS_FS_NAME=@@{NUS_FS_NAME}@@
export NUS_FS_API_USER=@@{NUS_FS_API_USER}@@
export NUS_FS_API_PASSWORD=@@{NUS_FS_API_PASSWORD}@@
export FILES_CREDS_STRING="@@{NUS_FS_NAME}@@.ntnxlab.local:@@{NUS_FS_API_USER}@@:@@{NUS_FS_API_PASSWORD}@@"
# NAI
export NAI_CORE_VERSION="@@{NAI_CORE_VERSION}@@"
export NKP_WORKSPACE=kommander-workspace
export NKP_NAMESPACE=kommander
EOF