#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

source ~/.env

if [[ @@{ERAG}@@ != "true" ]]; then
    echo "eRAG marked False or unset, skipping"
    exit 0
fi

# --- Variables ---
REPO_DIR="$HOME/Enterprise-RAG"
DEPLOY_DIR="$REPO_DIR/deployment"
VENV="$DEPLOY_DIR/erag-venv"
CONFIG_FILE="inventory/sample/config.yaml"
SOLUTION_CONFIG_FILE="roles/application/pre_install/tasks/solution_config.yaml"

# --- Functions ---

clone_erag_repo() {
    echo "--- Cloning eRAG Repo ---"
    if [ ! -d "$REPO_DIR" ]; then
        git clone --branch $ERAG_VERSION --depth 1 https://github.com/opea-project/Enterprise-RAG "$REPO_DIR" 
    else
        echo "Repo already exists, skipping clone."
    fi
}

configure_ansible_log() {
    echo "--- Configuring ansible log path ---"
    cd "$DEPLOY_DIR"
    grep -q "\[defaults\]" ansible.cfg && \
        sed -i '/\[defaults\]/a log_path = ./ansible.log' ansible.cfg || \
        echo -e "[defaults]\nlog_path = ./ansible.log" >> ansible.cfg
}

configure_config_yaml() {
    echo "--- Configuring config.yaml ---"

    cd "$DEPLOY_DIR"
    yq e '.kubeconfig = strenv(PATH_TO_ERAG_KUBECFG)' -i "$CONFIG_FILE"
    yq e '.FQDN = strenv(FQDN)' -i "$CONFIG_FILE"
    yq e '.install_csi = "nfs"' -i "$CONFIG_FILE"
    yq e '.ingress.service_type = "LoadBalancer"' -i "$CONFIG_FILE"
    yq e '.balloons.enabled = false' -i "$CONFIG_FILE"
    yq e '.registry = "registry.nutanixdemo.com/bootcamps/intel-erag"' -i "$CONFIG_FILE"

    # Validation
    yq e '.kubeconfig, .FQDN, .telemetry, .install_csi, .ingress, .registry' "$CONFIG_FILE" --no-colors
}

configure_domain_names() {
    echo "--- Configuring domain name prefixes in solution_config.yaml ---"

    cd "$DEPLOY_DIR"	
    yq -e "(.[] | select(.name == \"Set facts for domain names if not defined\") | .\"ansible.builtin.set_fact\") |=
      with_entries(
        .value |= (
          sub(\"'domainName': 'auth.'\"; \"'domainName': 'auth-'\") |
          sub(\"'domainName': 'grafana.'\"; \"'domainName': 'grafana-'\") |
          sub(\"'domainName': 'minio.'\"; \"'domainName': 'minio-'\") |
          sub(\"'apiDomainName': 's3.'\"; \"'apiDomainName': 's3-'\")
        )
      )" -i "$SOLUTION_CONFIG_FILE"
}

configure_venv() {
    echo "--- Configuring VENV ---"
    if [ ! -d "$VENV" ]; then
        python3 -m venv "$VENV"
    fi
    "$VENV/bin/python" -m pip install --upgrade pip
    "$VENV/bin/pip" install -r "$DEPLOY_DIR/requirements.txt"
}

install_ansible_collection() {
    echo "--- Installing Ansible collection ---"
    "$VENV/bin/ansible-galaxy" collection install -r "$DEPLOY_DIR/requirements.yaml" --upgrade
}

configure_llm_endpoint() {
    echo "--- Configuring LLM endpoint ---"
    export LLM_MODEL_NAME="llama31-8b-hf"
    export LLM_ENDPOINT="https://nai.tmelab.net/enterpriseai"
    export LLM_API_KEY="ee5975c3-78b6-4538-81d3-a186157c526d"

    cd "$DEPLOY_DIR"
    yq e '.pipelines[0].samplePath = "chatqa/reference-external-endpoint.yaml"' -i "$CONFIG_FILE"
    yq e '.pipelines[0].resourcesPath = "chatqa/resources-reference-external-endpoint.yaml"' -i "$CONFIG_FILE"

    yq e '(.spec.nodes.root.steps[] | select(.name == "Llm")).internalService.config |= ( 
        .endpoint = "/v1/chat/completions" |
        .LLM_MODEL_SERVER = "vllm" |
        .LLM_MODEL_NAME = strenv(LLM_MODEL_NAME) | 
        .LLM_MODEL_SERVER_ENDPOINT = strenv(LLM_ENDPOINT) |
        .LLM_VLLM_API_KEY = strenv(LLM_API_KEY)
    )' -i "pipelines/chatqa/reference-external-endpoint.yaml"

    yq '.spec.nodes.root.steps[] | select(.name == "Llm")' "pipelines/chatqa/reference-external-endpoint.yaml" --no-colors
}

adding_certs() {
    echo "--- Adding certs ---"
    export CERT_PATH="$HOME/certs/fullchain1.pem"
    export KEY_PATH="$HOME/certs/privkey1.pem"
    
    mkdir -p "$HOME/certs"
    wget -qO "$CERT_PATH" http://10.55.251.38/workshop_staging/tradeshows/configuration/certificates/sslip.nutanixdemo.com/fullchain1.pem 
    wget -qO "$KEY_PATH" http://10.55.251.38/workshop_staging/tradeshows/configuration/certificates/sslip.nutanixdemo.com/privkey1.pem

    cd "$DEPLOY_DIR"
    yq e '.certs.autoGenerated = false' -i "$CONFIG_FILE"
    yq e '.certs.pathToCert = strenv(CERT_PATH)' -i "$CONFIG_FILE"
    yq e '.certs.pathToKey = strenv(KEY_PATH)' -i "$CONFIG_FILE"
    yq e .certs "$CONFIG_FILE" --no-colors
}

configure_storage() {
    echo "--- Configuring storage ---"
    kubectl patch storageclass nutanix-files -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
    kubectl patch storageclass nutanix-volume -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

    cd "$DEPLOY_DIR"
    yq e '.gmc.pvc.accessMode = "ReadWriteMany"' -i "$CONFIG_FILE"
    yq e '.install_csi, .gmc' "$CONFIG_FILE" --no-colors
}

install_erag() {
    echo "--- Installing erag ---"
    cd "$DEPLOY_DIR"
    "$VENV/bin/ansible-playbook" -u "$USER" playbooks/application.yaml \
        --tags configure,install \
        -e "@./$CONFIG_FILE"
}

# --- Main Logic ---

echo "Starting eRAG installation process..."

clone_erag_repo
configure_ansible_log
configure_config_yaml
configure_domain_names
configure_venv
install_ansible_collection
configure_llm_endpoint
adding_certs
configure_storage
install_erag

echo "Installation Complete!"

# Get Keycloak admin password for creating users
cd "$DEPLOY_DIR"
cat <<EOF >>~/.env
export KEYCLOAK_ADMIN_PW=$(cat ansible-logs/default_credentials.* | grep KEYCLOAK_REALM_ADMIN_PASSWORD | awk '{print "\"" $2 "\""}')
EOF

echo "ERAG_FQDN=https://$FQDN"