apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: test-rwx-pvc # Replace with your PVC name
  containers:
    - name: busybox-container
      image: busybox
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"] # Keeps the pod running
      volumeMounts:
        - name: my-storage
          mountPath: /mnt/data # Mount point inside the container