#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "Creating .env file"
cat <<EOF >>~/.env
# NKP
export NKP_VERSION=$(nkp version -o=json |jq -r '.nkp.gitVersion')
export CLUSTER_NAME="@@{CLUSTER_NAME}@@"
export NUTANIX_USER="@@{CRED_PC.username}@@"
export NUTANIX_PASSWORD="@@{CRED_PC.secret}@@"
export NUTANIX_ENDPOINT="@@{PC_ADDRESS}@@"
export NUTANIX_PORT="@@{PC_PORT}@@"
export MGMT_LB_IP_RANGE_STARTS="@@{MGMT_LB_IP_RANGE_STARTS}@@"
export MGMT_LB_IP_RANGE_ENDS="@@{MGMT_LB_IP_RANGE_ENDS}@@"
export CONTROL_PLANE_VIP_ADDRESS="@@{CONTROL_PLANE_VIP_ADDRESS}@@"
export NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME="@@{MACHINE_TEMPLATE_IMAGE_NAME}@@"
export NUTANIX_PRISM_ELEMENT_CLUSTER_NAME="@@{PRISM_ELEMENT_CLUSTER_NAME}@@"
export NUTANIX_SUBNET_NAME="@@{SUBNET_NAME}@@"
export NUTANIX_STORAGE_CONTAINER_NAME="@@{STORAGE_CONTAINER_NAME}@@"
export REGISTRY_MIRROR_URL="@@{CONTAINER_REGISTRY_MIRROR}@@"
export NAI_IMAGE_REGISTRY="@@{NAI_IMAGE_REGISTRY}@@"
export REGISTRY_USERNAME="@@{CONTAINER_REGISTRY_USERNAME}@@"
export NO_COLOR=1
export MGMT_LB_IP_RANGE_USERS_STARTS="@@{MGMT_LB_IP_RANGE_USERS_STARTS}@@"
export MGMT_LB_IP_RANGE_USERS_ENDS="@@{MGMT_LB_IP_RANGE_USERS_ENDS}@@"
# LDAP
export DOMAIN=@@{DOMAIN}@@
export BINDDN='@@{BINDDN}@@'
export BINDPW='@@{BINDPW}@@'
export LDAP_HOST=@@{LDAP_HOST}@@
export LDAP_PORT='@@{LDAP_PORT}@@'
export NO_SSL='@@{NO_SSL}@@'
export SKIP_SSL_VERIFICATION='@@{SKIP_SSL_VERIFICATION}@@'
export START_TLS='@@{START_TLS}@@'
export LDAP_SEARCH_USERS='@@{LDAP_SEARCH_USERS}@@'
export LDAP_SEARCH_GROUPS='@@{LDAP_SEARCH_GROUPS}@@'
# Management Workspace
export MANAGEMENT_WORKSPACE_APPS='@@{MANAGEMENT_WORKSPACE_APPS}@@'
# Default Workspace
export INFRA_PROVIDER_NAME=pc
export DEFAULT_WORKSPACE_APPS='@@{DEFAULT_WORKSPACE_APPS}@@'
# CSI Files
export PE_VIP_ADDRESS=@@{PE_VIP_ADDRESS}@@
export NUS_FS_NAME=@@{NUS_FS_NAME}@@
export NUS_FS_API_USER=@@{NUS_FS_API_USER}@@
export NUS_FS_API_PASSWORD=@@{NUS_FS_API_PASSWORD}@@
export FILES_CREDS_STRING="@@{NUS_FS_NAME}@@.ntnxlab.local:@@{NUS_FS_API_USER}@@:@@{NUS_FS_API_PASSWORD}@@"
# NAI
export NAI_CORE_VERSION="@@{NAI_CORE_VERSION}@@"
export NKP_WORKSPACE=kommander-workspace
export NKP_NAMESPACE=kommander
# Objects
export NUS_OBJ_NAME="@@{NUS_OBJ_NAME}@@"
export OBJ_CONFIG_SCRIPT="@@{OBJ_CONFIG_SCRIPT}@@"
# Sizing
export NO_OF_USERS="@@{NO_OF_USERS}@@"
export NO_OF_WORKER_NODES="@@{NO_OF_WORKER_NODES}@@"
EOF

echo "Creating .secrets file"
cat <<EOF >>~/.secrets
export REGISTRY_PASSWORD="@@{CONTAINER_REGISTRY_PASSWORD}@@"
export NAI_DEFAULT_PW="@@{NAI_DEFAULT_PW}@@"
export NAI_NEW_ADMIN_PW="@@{NAI_NEW_ADMIN_PW}@@"
export HF_TOKEN="@@{HF_TOKEN}@@"
export LICENSE_KEY="@@{NAI_LICENSE_KEY}@@"
export LICENSE_CLUSTER_UUID="@@{NAI_LICENSE_UUID}@@"
export NAI_NEW_USER_PW="@@{NAI_NEW_USER_PW}@@"
export PC_ADDRESS="@@{PC_ADDRESS}@@"
export PC_PORT="@@{PC_PORT}@@"
export PC_USERNAME="@@{CRED_PC.username}@@" 
export PC_PASSWORD="@@{CRED_PC.secret}@@"
export DOMAIN="@@{DOMAIN}@@"
EOF